### ISSUE TITLE
Issues running go samples

### ISSUE THREAD

**Issue by david-r-bell** [ibm-messaging/mq-dev-patterns#12]
As I've been working through the Go samples on a Mac, I've hit the following issues:

 - Missing pre-req
The pre-req stated here: https://github.com/ibm-messaging/mq-dev-patterns/tree/master/Go#install-mq-golang-pre-reqs states you should run `go install ./mq-golang/ibmmq`. However, this will fail if you have not performed `sudo ln -s <unzip location>/IBM-MQ-Toolkit-Mac-x64-9.1.1.0 /opt/mqm` which is not mentioned until further down the page. This needs to be in the pre-reqs section or at least somewhere above the statement to run `go install ./mq-golang/ibmmq`.

- typos 
There are a large number of places where `environment` is misspelt as `envrionment`. FYI, I actually found this from the following line.:
```Env: 2020/03/05 14:47:48 CCDT URL export is not set, will be using json envrionment client connections settings```

- logging text
The first logging line in getMessage() in basicsub.go actually logs 'Writing Message to Queue`:
```
func getMessage(qObject ibmmq.MQObject) {
	logger.Println("Writing Message to Queue")
```

- request/response sample not working for me
I was able to run the put/get and pub/sub samples, but using all the same settings, and having created a new Model Queue called `DEV.APP.MODEL.QUEUE`, the request/response sample didn't work for me. The basicrequest sample failed as follows (with some values removed):
```
$ ./basicrequest 
Env: 2020/03/05 16:25:39 Successfully Opened env.json
Env: 2020/03/05 16:25:39 Looking for Envrionment Overrides
Env: 2020/03/05 16:25:39 Overide for PORT
Env: 2020/03/05 16:25:39 Overide for CHANNEL
Env: 2020/03/05 16:25:39 Overide for QMGR
Env: 2020/03/05 16:25:39 Overide for MODEL_QUEUE_NAME
Env: 2020/03/05 16:25:39 Overide for DYNAMIC_QUEUE_PREFIX
Env: 2020/03/05 16:25:39 Overide for HOST
Env: 2020/03/05 16:25:39 Overide for KEY_REPOSITORY
Env: 2020/03/05 16:25:39 Overide for CIPHER
Env: 2020/03/05 16:25:39 Overide for APP_USER
Env: 2020/03/05 16:25:39 Overide for APP_PASSWORD
Env: 2020/03/05 16:25:39 Overide for QUEUE_NAME
Env: 2020/03/05 16:25:39 Overide for TOPIC_NAME
MQ Request: 2020/03/05 16:25:39 Application is Starting
MQ Request: 2020/03/05 16:25:39 Username is (appuser)
Env: 2020/03/05 16:25:39 Envrionment Settings are
Env: 2020/03/05 16:25:39 Username is (appuser)
Env: 2020/03/05 16:25:39 Queue Manager is (drb_5mar20)
Env: 2020/03/05 16:25:39 Queue Name is (DEV.QUEUE.1)
Env: 2020/03/05 16:25:39 ModelQueue Name is (DEV.APP.MODEL.QUEUE)
Env: 2020/03/05 16:25:39 Host is (removed)
Env: 2020/03/05 16:25:39 Port is (removed)
Env: 2020/03/05 16:25:39 Connection is (removed(removed))
Env: 2020/03/05 16:25:39 Channel is (CLOUD.APP.SVRCONN)
Env: 2020/03/05 16:25:39 Topic is (dev/)
Env: 2020/03/05 16:25:39 Key Respository is ()
Env: 2020/03/05 16:25:39 Cipher ()
Env: 2020/03/05 16:25:39 Setting up Connection to MQ
Env: 2020/03/05 16:25:39 User appuser has been specified
Env: 2020/03/05 16:25:39 CCDT URL export is not set, will be using json envrionment client connections settings
Env: 2020/03/05 16:25:39 Connecting to removed(removed) 
Env: 2020/03/05 16:25:39 Attempting connection to drb_5mar20
Env: 2020/03/05 16:25:41 Connection succeeded
Env: 2020/03/05 16:25:41 Attempting open queue/topic DEV.QUEUE.1
Env: 2020/03/05 16:25:41 Opened queue/topic DEV.QUEUE.1
Env: 2020/03/05 16:25:41 Attempting open queue/topic DEV.QUEUE.1
Env: 2020/03/05 16:25:41 MQOPEN: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035]
Env: 2020/03/05 16:25:41 Error Code 2
MQ Request: 2020/03/05 16:25:41 Unable to Open Dynamic Queue
```
My env.json file looks as follows:
{
  "MQ_ENDPOINTS": [{
    "HOST": "removed",
    "PORT": "removed",
    "CHANNEL": "CLOUD.APP.SVRCONN",
    "QMGR": "drb_5mar20",
    "APP_USER": "appuser",
    "APP_PASSWORD": "removed",
    "QUEUE_NAME": "DEV.QUEUE.1",
    "MODEL_QUEUE_NAME": "DEV.APP.MODEL.QUEUE",
    "DYNAMIC_QUEUE_PREFIX": "APP.REPLIES.*",
    "TOPIC_NAME": "dev/"
  }]
}

**Comment by chughts** [comment]
The not authorised is for the dynamic queue. I think what will be happening is that your `appuaser` doesn't have the appropriate read authorisation for the model `DEV.APP.MODEL.QUEUE`.

**Comment by david-bell-ibm** [comment]
Thanks @chughts. I got this working.

I think this needs adding to the readme too.It may also help the user to be clearer whether the intention is to read all the main readme here: https://github.com/ibm-messaging/mq-dev-patterns AND the language specific readme here: https://github.com/ibm-messaging/mq-dev-patterns/tree/master/Go

I certainly had to read all of both, in order to spot each bit of information I needed.
For example, I the requirement that I create a MODEL queue I found after the original failure, by reading all of the main readme and finding the line just before: https://github.com/ibm-messaging/mq-dev-patterns#environment-variables. However, this did not mention the need to also add the permissions for the app user. FYI, I found the minimum permissions I needed to add were by:
 - in Web console, select the MODEL you just created, e.g.: DEV.APP.MODEL.QUEUE
 - select the three dots in the menu bar
 - select `Manage authority records...`
 - click `Create +`
 - enter the app user you are using
 - leave User specified
 - click Create
 - select new user
 - tick only `Display` under Administration
 - click `Save`

The request sample should now run successfully.

**Comment by chughts** [comment]
@david-bell-ibm thanks for the input. We are looking to see how we can modify the readme structure, so that it is clearer, but without having to duplicate content.
